stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: "yourusername/coffee-bliss"
  TAG: "latest"
  DOCKER_REGISTRY: "docker.io"  


test:
  stage: test
  script:
    - echo "Running tests..."
    - docker-compose up -d  
    - sleep 10  
    - curl -f http://localhost:8080 || exit 1  
    - docker-compose down  
  only:
    - main  


build:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$TAG .
    - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$TAG
  only:
    - main


deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
    - ssh ubuntu@192.168.0.100 "docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$TAG && docker-compose up -d"
  only:
    - main
